server:
  port: 8088
  servlet:
    context-path: /
    tomcat:
      accept-count: 1000
      accesslog:
        directory: ./logs
        enabled: true
        encoding: UTF-8
        file-date-format: yyyy-MM-dd HH:mm:ss
        max-days: 7
        pattern: '%t %h "%r" %s (%D ms, %b bytes)'
        prefix: access_log.
        request-attributes-enabled: true
        rotate: true
        suffix: .log
      connection-timeout: 30
      keep-alive-timeout: 30
      max-connections: 200
      max-http-form-post-size: 2097152
      max-http-response-header-size: 8192
      max-keep-alive-requests: -1
      max-parameter-count: 256
      threads:
        max: 16
        max-queue-capacity: 1024
        min-spare: 8
      uri-encoding: UTF-8

spring:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&rewriteBatchStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: HikariCP
    minimum-idle: 5
    idle-timeout: 600000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: select 1 from dual
    registerMbeans: false
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 200
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

  logging:
    level:
      com.zaxxer.hikari.HikariConfig: DEBUG
      com.zaxxer.hikari: TRACE
      com.zaxxer.hikari.pool.HikariPool: INFO
      com.zaxxer.hikari.pool.ProxyConnection: WARN